# Generated by Django 4.1.3 on 2023-01-23 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_words_starred1_user_and_session1'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='user_and_session',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='words.user_and_session'),
        ),
    ]
